Clinica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
    path('users/', include("login.urls"))
]

index/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.index, name="index"),
    path('Prader-Wili/ghiduri/', views.ghiduri, name='ghiduri'),
    path('Prader-Wili/protocoale/', views.protocoale, name='protocoale'),
    path('Prader-Wili/diagnostic/', views.diagnostic, name='diagnostic'),
    path('Prader-Wili/tratament-gh/', views.tratament_gh, name='tratament_gh'),
    path('Prader-Wili/tratament/', views.tratament, name='tratament'),
    path('Prader-Wili/evaluare-initiala/', views.evaluare_initiala, name='evaluare_initiala'),
    path('Prader-Wili/laboratoare-diagnostic/', views.laboratoare_diagnostic, name='laboratoare_diagnostic'),
    path('Prader-Wili/clinici-ingrijire/', views.clinici_ingrijire, name='clinici_ingrijire'),
    path('Prader-Wili/alerte/', views.alerte, name='alerte'),
    path('Obezitati-Rare/patologii/', views.patologii, name='patologii'),
    path('Obezitati-Rare/tratament-obezitati/', views.tratament_obezitati, name='tratament_obezitati'),
    path('Obezitati-Rare/monitorizare/', views.monitorizare, name='monitorizare'),
    path('Obezitati-Rare/laboratoare-diagnostic-obezitati/', views.laboratoare_diagnostic_obezitati, name='laboratoare_diagnostic_obezitati'),
    path('Obezitati-Rare/clinici-ingrijire-obezitati/', views.clinici_ingrijire_obezitati, name='clinici_ingrijire_obezitati'),
    path('Traseul-pacientului/centre-de-ingrijire/', views.centre_de_ingrijire, name='centre_de_ingrijire'),
    path('Traseul-pacientului/asociatii-de-pacienti/', views.asociatii_de_pacienti, name='asociatii_de_pacienti'),
    path('Traseul-pacientului/medico-social/', views.medico_social, name='medico_social'),
    path('Traseul-pacientului/viata-scolara/', views.viata_scolara, name='viata_scolara'),
    path('Traseul-pacientului/viata-sociala/', views.viata_sociala, name='viata_sociala'),
    path('Traseul-pacientului/proiecte-de-viata/', views.proiecte_de_viata, name='proiecte_de_viata'),
    path('Traseul-pacientului/formare-profesionala/', views.formare_profesionala, name='formare_profesionala'),
    path('Traseul-pacientului/hobby/', views.hobby, name='hobby'),
    path('Traseul-pacientului/servicii-sociale/', views.servicii_sociale, name='servicii_sociale'),
    path('Traseul-pacientului/tranzitia-adolescent-adult/', views.tranzitia_adolescent_adult, name='tranzitia_adolescent_adult'),
    path('Traseul-pacientului/urgente-si-riscuri-de-decompensare/', views.urgente_si_riscuri_de_decompensare, name='urgente_si_riscuri_de_decompensare'),
    path('Traseul-pacientului/calatorii/', views.calatorii, name='calatorii'),
    path('Traseul-pacientului/screening/', views.screening, name='screening'),
    path('Traseul-pacientului/forum-de-discutii/', views.forum_de_discutii, name='forum_de_discutii'),
    path('Traseul-pacientului/cercetare-clinica/', views.cercetare_clinica, name='cercetare_clinica'),
    path('Traseul-pacientului/centre-de-expertiza/', views.centre_de_expertiza, name='centre_de_expertiza'),
    path('Traseul-pacientului/servici-medicale/', views.servici_medicale, name='servici_medicale'),
    path('Traseul-pacientului/educatia-familiei-si-a-institutiilor/', views.educatia_familiei_si_a_institutiilor, name='educatia_familiei_si_a_institutiilor'),
    path('Traseul-pacientului/comportament/', views.comportament, name='comportament'),
    path('Educatia-terapeutica/instrumente-dieta/', views.instrumente_dieta, name='instrumente_dieta'),
    path('Educatia-terapeutica/workshop/', views.workshop, name='workshop'),
    path('Educatia-terapeutica/retete-culinare/', views.retete_culinare, name='retete_culinare'),
    path('Educatia-terapeutica/ingrijire/', views.ingrijire, name='ingrijire'),
    path('Educatia-terapeutica/aspecte-psihologice/', views.aspecte_psihologice, name='aspecte_psihologice'),
    path('Educatia-terapeutica/activitate-fizica/', views.activitate_fizica, name='activitate_fizica'),
    path('Educatia-terapeutica/instrumente-practice-de-ingrijire/', views.instrumente_practice_de_ingrijire, name='instrumente_practice_ingrijire'),
    path('Educatia-terapeutica/tratamentul-cu-hormon-de-crestere/', views.tratamentul_cu_hormon_de_crestere, name='tratament_hormon_crestere'),
    path('Educatia-terapeutica/link-uri-utile/', views.link_uri_utile, name='linkuri_utile'),
    path('Educatia-terapeutica/recomandari/', views.recomandari, name='recomandari'),

    path('Echipa-multidisciplinara/profesionisti-implicati/', views.profesionisti_implicati, name='profesionisti_implicati'),
    path('Echipa-multidisciplinara/plan-actiune/', views.plan_actiune, name='plan_actiune'),
    path('Echipa-multidisciplinara/grupuri-lucru/', views.grupuri_lucru, name='grupuri_lucru'),
    path('Echipa-multidisciplinara/plan-intalniri/', views.plan_intalniri, name='plan_intalniri'),
    path('Echipa-multidisciplinara/cpms/', views.cpms, name='cpms'),
    path('Echipa-multidisciplinara/plan-boli-rare/', views.plan_boli_rare, name='plan_boli_rare'),
    path('Echipa-multidisciplinara/parteneri/', views.parteneri, name='parteneri'),

    path('Formare-informare/evenimente/', views.evenimente, name='evenimente'),
    path('Formare-informare/newsletter/', views.newsletter, name='newsletter'),
    path('Formare-informare/radio-noro/', views.radio_noro, name='radio_noro'),
    path('Formare-informare/webinar/', views.webinar, name='webinar'),
    path('Formare-informare/tutoriale/', views.tutoriale, name='tutoriale'),
    path('Formare-informare/podcast/', views.podcast, name='podcast'),
    path('Formare-informare/video/', views.video, name='video'),
    path('Formare-informare/formare-pentru-medici/', views.formare_pentru_medici, name='formare_pentru_medici'),
    path('Formare-informare/formare-pentru-pacienti/', views.formare_pentru_pacienti, name='formare_pentru_pacienti'),

    path('Cercetare/actualitati/', views.actualitati, name='actualitati'),
    path('Cercetare/tipuri-de-cercetare/', views.tipuri_de_cercetare, name='tipuri_de_cercetare'),
    path('Cercetare/cercetare-europa/', views.cercetare_europa, name='cercetare_europa'),

    path('Tratamentul_GH/protocol-de-tratament/', views.protocol_de_tratament, name='protocol_de_tratament'),
    path('Tratamentul_GH/informatii-despre-medicament/', views.informatii_despre_medicament, name='informatii_despre_medicament'),
    path('Tratamentul_GH/protocoale-terapeutice/', views.protocoale_terapeutice, name='protocoale_terapeutice'),
    path('Tratamentul_GH/monitorizarea-tratamentului/', views.monitorizarea_tratamentului, name='monitorizarea_tratamentului'),
    path('Test/', views.Test, name='Test'),
    path('Trasaturi_clinice/', views.Trasaturi_clinice, name='Trasaturi_clinice'),
    path('Obezitate/', views.Obezitate, name='Obezitate'),
    path('Comportament/', views.Comportament, name='Comportament'),
    path('Criterii_clinice/', views.Criterii_clinice, name='Criterii_clinice'),
    path('Criterii_obezitate/', views.Criterii_obezitate, name='Criterii_obezitate'),
    path('Diagnostic_genetic/', views.Diagnostic_genetic, name='Diagnostic_genetic'),
    path('Genetica_regiunii/', views.Genetica_regiunii, name='Genetica_regiunii'),
    path('Modificari_genetice/', views.Modificari_genetice, name='Modificari_genetice'),
    path('Testare_genetica/', views.Testare_genetica, name='Testare_genetica'),
    path('Algoritm_testare_genetica/', views.Algoritm_testare_genetica, name='Algoritm_testare_genetica'),
    path('Sfat_genetic/', views.Sfat_genetic, name='Sfat_genetic'),
    path('Corelatii_genotip_fenotip/', views.Corelatii_genotip_fenotip, name='Corelatii_genotip_fenotip'),
    path('Diagnostic_prenatal/', views.Diagnostic_prenatal, name='Diagnostic_prenatal'),
    path('Diagnostic_diferential/', views.Diagnostic_diferential, name='Diagnostic_diferential'),
    path('tratamentGH_copii/', views.tratamentGH_copii, name='tratamentGH_copii'),
    path('tratamentGH_adulti/', views.tratamentGH_adulti, name='tratamentGH_adulti'),
    path('tratamentGH_tranzitie/', views.tratamentGH_tranzitie, name='tratamentGH_tranzitie'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.dash_view, name='dash'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('verify-email/<uuid:token>/', views.verify_email, name='verify_email'),
    path('long/Test/', views.Test, name='Test')
]

login/models.py
from django.contrib.auth.models import User
from django.db import models
import uuid

class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES)
    email_verified = models.BooleanField(default=False)
    verification_token = models.UUIDField(default=uuid.uuid4, editable=False)
    code = models.CharField(max_length=10, default='0000')

    def __str__(self):
        return self.user.username

login/templates/login/Test.html
{% extends 'index/navbar.html'%}
{% load static %}
{% load custom_filters %}


<!DOCTYPE html>
<html lang="en">
{%block content%}

<head>

    <title>Prader-Wili</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="apple-touch-icon" type="image/png"
        href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png">
    <link rel="shortcut icon" type="image/x-icon"
        href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico">
    <link rel="mask-icon" type="image/x-icon"
        href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg"
        color="#111">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="{% static 'index/style.css' %}">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
        crossorigin="anonymous" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
        crossorigin="anonymous" />

    <style>
        /* Scoped styles for the cute links container */
        .cute-links-container {
            font-family: 'Arial', sans-serif;
            background-color: #f9f9f9;
            padding: 20px;
        }

        .cute-links-container ul {
            list-style: none;
            padding: 0;
        }

        .cute-links-container ul li {
            margin: 10px 0;
        }

        .cute-links-container ul li a {
            display: flex;
            align-items: center;
            text-decoration: none;
            color: #333;
            font-size: 18px;
            padding: 10px;
            border-radius: 8px;
            background-color: #fff;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            transition: all 0.3s ease;
        }

        .cute-links-container ul li a:hover {
            background-color: #e7f3ff;
            box-shadow: 0 6px 10px rgba(0, 0, 0, 0.15);
            color: #007BFF;
        }

        .cute-links-container ul li a::before {
            content: "🔗";
            margin-right: 10px;
            font-size: 20px;
        }

        /*CSS PENTRU CARDURILE ADUGATE DE LIDIA*/
        .card-container {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: center;
            padding: 20px;
        }

        .card {
            background-color: #f9fbfd;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            flex: 1 1 calc(33.333% - 20px);
            max-width: 400px;
            text-align: center;
            box-sizing: border-box;
            border: 1px solid #e0e0e0;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .card h3 {
            font-size: 1.5rem;
            color: #005bbf;
            margin-bottom: 10px;
        }

        .card p {
            font-size: 1rem;
            color: #333;
            line-height: 1.5;
            margin-bottom: 20px;
        }

        .details-btn {
            font-size: 1rem;
            color: #005bbf;
            text-decoration: none;
            cursor: pointer;
            font-weight: bold;
            padding-top: 10px;
            border-top: 1px solid #e0e0e0;
        }

        .details-btn a {
            color: #005bbf;
            text-decoration: none;
        }

        .details-btn a:hover {
            text-decoration: underline;
        }

        @media (max-width: 768px) {
            .card {
                flex: 1 1 calc(50% - 20px);
            }
        }

        @media (max-width: 480px) {
            .card {
                flex: 1 1 100%;
            }
        }

        /*CSS PENTRU CARUSELUL LUI CATA*/
        .item {
            transition: transform 0.3s ease;
            /* Smooth transition for scaling */
            cursor: pointer;
            /* Indicate that the item is clickable */
        }

        .item:hover {
            transform: scale(1.05);
            /* Scale the card on hover */
        }

        .item-desc {
            position: relative;
            z-index: 1;
            /* Ensure text appears above the background */
            padding: 10px;
            /* Add some padding */
            color: white;
            /* Adjust text color for visibility */
        }
        @media (max-width: 768px) {
            body {
                font-size: 1.2rem;
            }

            th,
            td {
                padding: 8px;
            }
        }

        /* Media query for extra-small devices (small phones) */
        @media (max-width: 480px) {
            body {
                font-size: 1rem;
            }

            th,
            td {
                padding: 6px;
            }
        }
    </style>
    <title>Styled Links</title>



</head>


<body>

    <!-- Script section -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <script>
        AOS.init();
    </script>
    <script src="{% static 'index/scripts.js' %}"></script>
    <!--Bootsrap scripts-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
        integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
        crossorigin="anonymous"></script>

    <div class="photo-section" id="home">
        <img class="photo_art" src="{% static 'index/Resources/work_in_progress.jpg' %}" alt="Descriptive Alt Text">
    </div>




</body>
{%endblock%}

</html>

login/templates/login/index.html
{% extends 'login/navbar.html'%}
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">  
    <head>
        <title>Account</title>
    </head>

    <body>

        {% block content %}
        <div class="form-container">
            <h1 class="header">Welcome, {{request.user.username}}</h1>
            <p class="paragraph">
                User Type: {{ user_type }}
            </p>
            <p class="paragraph">
                Verified user: {{ email_verified }}
            </p>
            <form class="form" action="{% url 'login:index' %}" method="post">
                {% csrf_token %}
                <p class="title">Your account </p>
                <p class="message">Here is the dashboard for your account</p>
                    <div class="flex">
                        
                    <label>
                        <input class="input"  type="text" placeholder="{{request.user.first_name}}" name="first_name">
                        <span>Firstname</span>
                    </label>
                        
                    <label>
                        <input class="input"  type="text" placeholder="{{request.user.last_name}}" name="last_name">
                        <span>Lastname</span>
                    </label>
                </div>  
                        
                
                <label>
                    <input class="input" type="text" placeholder="{{request.user.username}}" name="username">
                    <span>Username</span>
                </label> 
                
                <p class="signin">Change password</p>
                <label>
                    <input class="input" type="password" placeholder="" name="password">
                    <span>Password</span>
                </label>
                <label>
                    <input class="input" type="password" placeholder="" name="password_confirm">
                    <span>Confirm password</span>
                </label>
                
                <label>
                    <input class="input" type="text" placeholder="{{request.user.email}}" name="email">
                    <span>Email</span>
                </label> 
                {% if user_type == "patient" %}
                    <label>
                        <input class="input" type="text" placeholder="{{code}}" name="code">
                        <span>Assignment Code</span>
                    </label> 
                        Your doctor with the same code: {{doctor}}
                {% else %}
                        Your code is: {{code}}
                {% endif %}
                
                <button class="submit" type="submit" value="Change" name="Change">Change</button>
                <button class="submit" type="submit" value="Register" href="{% url 'login:logout' %}" name="Logout">Log out</button>
            </form>
            </div>

            
        <!-- <form action="{% url 'login:index' %}" method="post">
            {% csrf_token %}
            {{request.user.first_name}}
            <input type="text" placeholder="First Name" name="first_name">
            <br>
            {{request.user.last_name}}
            <input type="text" placeholder="Last Name" name="last_name">
            <br>
            {{request.user.username}}
            <input type="text" placeholder="username" name="username">
            <br>
            <h1>Change Password</h1>
            <input type="password" placeholder="password" name="password">
            <br>
            <input type="password" placeholder="password Confirm" name="password_confirm">
            <br>
            {{request.user.email}}
            <input type="text" placeholder="New Email" name="email">
            <br>
            <input type="submit" value="Change">
        </form> -->

        {% if message %}
        <div>{{ message }}</div>
        {% endif %}

        <!-- <a href="{% url 'login:logout' %}">Logout</a> -->
        {% endblock %}
    </body>
    

login/templates/login/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <!--=============== REMIXICONS ===============-->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.css">

   <!--=============== CSS ===============-->
   <link rel="stylesheet" href="{% static 'login/css/styles.css' %}">
   
   <title>Responsive login and registration form - Bedimcode</title>
</head>

<body>
   <!--=============== LOGIN IMAGE ===============-->
   <svg class="login__blob" viewBox="0 0 566 840" xmlns="http://www.w3.org/2000/svg">
      <mask id="mask0" mask-type="alpha">
         <path d="M342.407 73.6315C388.53 56.4007 394.378 17.3643 391.538 
         0H566V840H0C14.5385 834.991 100.266 804.436 77.2046 707.263C49.6393 
         591.11 115.306 518.927 176.468 488.873C363.385 397.026 156.98 302.824 
         167.945 179.32C173.46 117.209 284.755 95.1699 342.407 73.6315Z"/>
      </mask>
   
      <g mask="url(#mask0)">
         <path d="M342.407 73.6315C388.53 56.4007 394.378 17.3643 391.538 
         0H566V840H0C14.5385 834.991 100.266 804.436 77.2046 707.263C49.6393 
         591.11 115.306 518.927 176.468 488.873C363.385 397.026 156.98 302.824 
         167.945 179.32C173.46 117.209 284.755 95.1699 342.407 73.6315Z"/>
   
         <!-- Insert your image (recommended size: 1000 x 1200) -->
         <image class="login__img" href="{% static 'login/img/bg-img.jpg' %}"/>
      </g>
   </svg>      

   <!--=============== LOGIN ===============-->
   <div class="login container grid" id="loginAccessRegister">
      <!--===== LOGIN ACCESS =====-->
      <div class="login__access">
         <h1 class="login__title">Log in to your account.</h1>
         {% if message %}
         <div>{{ message }}</div>
         {% endif %} 
         <div class="login__area">
            <form action="" class="login__form" action="{% url 'login:login' %}" method="post">
               {% csrf_token %}
               <div class="login__content grid">
                  <div class="login__box">
                     <input type="input" id="username" required placeholder=" " class="login__input" name = "username_login">
                     <label for="username" class="login__label">Username</label>
                  </div>
      
                  <div class="login__box">
                     <input type="password" id="password" required placeholder=" " class="login__input" name = "password_login">
                     <label for="password" class="login__label">Password</label>
         
                     <i class="ri-eye-off-fill login__icon login__password" id="loginPassword"></i>
                  </div>
               </div>
      
               <a href="#" class="login__forgot">Forgot your password?</a>
      
               <button type="submit" class="login__button" name="buton_login" value="buton_login">Login</button>
            </form>
   
            <p class="login__switch">
               Don't have an account? 
               <button id="loginButtonRegister">Create Account</button>
            </p>
         </div>
      </div>

      <!--===== LOGIN REGISTER =====-->
      <div class="login__register">
         <h1 class="login__title">Create new account.</h1>

         <div class="login__area">
            <form action="" class="login__form" method = "post" action="{% url 'login:login' %}">
               {% csrf_token %}
               <div class="login__content grid">
                  <div class="login__group grid">
                     <div class="login__box">
                        <input type="text" id="names" required placeholder=" " class="login__input" name="firstname">
                        <label for="names" class="login__label">Names</label>
   
                        <i class="ri-id-card-fill login__icon"></i>
                     </div>
   
                     <div class="login__box">
                        <input type="text" id="surnames" required placeholder=" " class="login__input" name="lastname">
                        <label for="surnames" class="login__label">Surnames</label>
   
                        <i class="ri-id-card-fill login__icon"></i>
                     </div>
                  </div>

                  <div class="login__box">
                     <input type="input" id="username" required placeholder=" " class="login__input" name="username">
                     <label for="username" class="login__label">Username</label>
                  </div>

                  <div class="login__box">
                     <input type="email" id="emailCreate" required placeholder=" " class="login__input" name="email">
                     <label for="emailCreate" class="login__label">Email</label>

                     <i class="ri-mail-fill login__icon"></i>
                  </div>

                  <div class="login__box">
                     <input type="password" id="passwordCreate" required placeholder=" " class="login__input" name="password">
                     <label for="passwordCreate" class="login__label" >Password</label>

                     <i class="ri-eye-off-fill login__icon login__password" id="loginPasswordCreate"></i>
                  </div>

                  <div class="login__box">
                     <input type="password" id="passwordCreate" required placeholder=" " class="login__input" name="password_confirm">
                     <label for="passwordCreate" class="login__label" >Password Confirm</label>

                     <i class="ri-eye-off-fill login__icon login__password" id="loginPasswordCreate"></i>
                  </div>
               
                  <label>
                     <select class="input" name="user_type"
                        style="background-color: #f4f6fb; color: #9ba4b5; width: 100%; padding: 20px 5px 5px 10px; outline: none; border: 1px solid rgba(105, 105, 105, 0.397); border-radius: 10px; font-weight: 600; font-size: 1rem;
                        text-align: center; /* Centers text in Chrome /
                        text-align-last: center; / Centers text in Firefox */">

                        <option value="patient"
                           style="font-weight: 600; font-size: 1rem; transition: transform .4s, font-size .4s, color .4s;">
                           Pacient
                        </option>
                        <option value="doctor"
                           style="font-weight: 600; font-size: 1rem; transition: transform .4s, font-size .4s, color .4s;">
                           Doctor
                        </option>
                     </select>
                  </label>
               </div>
               <button type="submit" class="login__button" name="buton_register" value="buton_register">Create account</button>
            </form>

            <p class="login__switch">
               Already have an account? 
               <button id="loginButtonAccess">Log In</button>
            </p>
         </div>
      </div>
   </div>
   
   <!--=============== MAIN JS ===============-->
   <script src="{% static 'login/js/main.js' %}"></script>

</body>

</html>